### ISSUE TITLE
Web üzerinde ev resmi görüntülensin

### ISSUE THREAD

**Issue by ozalpmurat** [AVRUPASYA/GomuluIsletimSistemler#2]
Bir ev resmi üzerinde düğmeler ve senör değerleri/durumları görüntülensin. Şuradaki gibi bir şey olabilir: https://www.cre8tiverooms.com/wp-content/uploads/2018/05/smart-home-website-updated-01.05.jpg

**Comment by OmerKarabalik** [comment]
tamamlandı!
