### ISSUE TITLE
README dosyası eksik

### ISSUE THREAD

**Issue by ozalpmurat** [AVRUPASYA/GomuluIsletimSistemler#5]
Sistem diyagramı demişsin, elle yazı olarak yazmışsın. Gerçek diyagram istiyorum yazı değil. Bloğumda yazdığım şeyleri istiyorum. Vizede bunlardan not kırmadım ama finalde kırılır. Şurayı dikkatli oku: http://web.bilecik.edu.tr/murat-ozalp/2018/12/06/gomulu-isletim-sistemleri-github-odevi/

**Comment by OmerKarabalik** [comment]
gerekeni yaptım inşaAllah!
